### ISSUE TITLE
riscv statically set here? 

### ISSUE THREAD

**Issue by noahbliss** [esp-rs/esp-mbedtls#26]
I'm a noob, but it seems that risc-v is set statically here when the rest of the file seems to follow an "xtensa or riscv" approach. Just pointing it out in-case it is something, feel free to close otherwise. :)

https://github.com/esp-rs/esp-mbedtls/blob/360bf597cba0d75732444da3fba3ee134b9afa9a/xtask/src/main.rs#L361

**Comment by bjoernQ** [comment]
Thanks! That line is just the host which shouldn't affect the build. 

The relevant line is https://github.com/esp-rs/esp-mbedtls/blob/360bf597cba0d75732444da3fba3ee134b9afa9a/xtask/src/main.rs#L360

There we define the compilation target
