### ISSUE TITLE
ESP32C6 support

### ISSUE THREAD

**Issue by therealchfkch** [esp-rs/esp-mbedtls#39]
Hello,
i have noticed that the C6 boards are not supported.
As an outsider with little understanding of the chip architecture i wanted to ask if supporting the C6 is a mere adjustment of numbers (i have glanced over the configuration include file - that's alot of stuff) or if there is more work to it.
Since i want to use the `reqwless` crate for my project, which depends on this one, i was curious if this could be done.
I am not sure i would be fit to contribute myself, but if it was just taking out numbers of datasheets and translate them to Rust Code, i might at least assist.
Maybe you can shine some light on this, since i cannot imagine if it is possible at all right now or if it is 10 hours of work or 100 ;)

Best regards

**Comment by bjoernQ** [comment]
In theory adding support for C6 should be pretty much straight forward and it should be even possible to use the precompiled `riscv32imc` binaries on C6 (while it's `riscv32imac`)

If you are fine with using TLS 1.3 you can also use `embedded-tls` instead (which needs much less resources)
